# Site settings
title: Yuhan Shi
description: Yuhan's Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yuhan Shi
user_description: I'm currently study in Computer Science, Mathematics, and Economics at University of Oregon. #Visit my Github page here <a href="https://github.com/missystem/" target="_blank">https://github.com/missystem/</a>
user_title: U of O - CIS x MATH x ECON
email: misy.shi@gmail.com
# twitter_username: lorem_ipsum
github_username:  missystem
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
